### data1

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed

import numpy as np # linear algebra

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [10]:

df1 = pd.read_excel('data (1).xlsx', header=2)

data=df1.values

print("all value we get:\n{}".format(data))

all value we get:
[['Albury - Adult AMHS' 'Apr - Jun 2020' 13.28]
 ['Albury - Adult AMHS' 'Jul - Sep 2020' 8.35]
 ['Albury - Adult AMHS' 'Oct - Dec 2020' 3.88]
 ['Albury - Adult AMHS' 'Jan - Mar 2021' 2.41]
 ['Albury - Adult AMHS' 'Apr - Jun 2021' 3.34]
 ['Barwon - AMHS' 'Apr - Jun 2020' 9.75]
 ['Barwon - AMHS' 'Jul - Sep 2020' 7.37]
 ['Barwon - AMHS' 'Oct - Dec 2020' 10.4]
 ['Barwon - AMHS' 'Jan - Mar 2021' 18.91]
 ['Barwon - AMHS' 'Apr - Jun 2021' 2.82]
 ['Central & Outer East - Aged AMHS' 'Apr - Jun 2020' 0.0]
 ['Central & Outer East - Aged AMHS' 'Jul - Sep 2020' 1.93]
 ['Central & Outer East - Aged AMHS' 'Oct - Dec 2020' 1.44]
 ['Central & Outer East - Aged AMHS' 'Jan - Mar 2021' 0.58]
 ['Central & Outer East - Aged AMHS' 'Apr - Jun 2021' 0.0]
 ['Central East - Adult AMHS' 'Apr - Jun 2020' 11.96]
 ['Central East - Adult AMHS' 'Jul - Sep 2020' 9.67]
 ['Central East - Adult AMHS' 'Oct - Dec 2020' 16.98]
 ['Central East - Adult AMHS' 'Jan - Mar 2021' 10.69]
 ['Central East - Adult AMHS' 'Apr - Jun 2021' 1.56]
 ['Dandenong - Adult AMHS' 'Apr - Jun 2020' 6.12]
 ['Dandenong - Adult AMHS' 'Jul - Sep 2020' 4.61]
 ['Dandenong - Adult AMHS' 'Oct - Dec 2020' 8.07]
 ['Dandenong - Adult AMHS' 'Jan - Mar 2021' 8.47]
 ['Dandenong - Adult AMHS' 'Apr - Jun 2021' 7.0]
 ['Eastern - CAMHS AMHS' 'Apr - Jun 2020' 22.7]
 ['Eastern - CAMHS AMHS' 'Jul - Sep 2020' 10.32]
 ['Eastern - CAMHS AMHS' 'Oct - Dec 2020' 13.09]
 ['Eastern - CAMHS AMHS' 'Jan - Mar 2021' 19.65]
 ['Eastern - CAMHS AMHS' 'Apr - Jun 2021' 19.18]
 ['Gippsland - AMHS' 'Apr - Jun 2020' 1.22]
 ['Gippsland - AMHS' 'Jul - Sep 2020' 0.0]
 ['Gippsland - AMHS' 'Oct - Dec 2020' 2.92]
 ['Gippsland - AMHS' 'Jan - Mar 2021' 3.36]
 ['Gippsland - AMHS' 'Apr - Jun 2021' 1.72]
 ['Glenelg - AMHS' 'Apr - Jun 2020' 11.66]
 ['Glenelg - AMHS' 'Jul - Sep 2020' 4.13]
 ['Glenelg - AMHS' 'Oct - Dec 2020' 5.94]
 ['Glenelg - AMHS' 'Jan - Mar 2021' 11.91]
 ['Glenelg - AMHS' 'Apr - Jun 2021' 0.83]
 ['Goulburn - AMHS' 'Apr - Jun 2020' 27.11]
 ['Goulburn - AMHS' 'Jul - Sep 2020' 8.39]
 ['Goulburn - AMHS' 'Oct - Dec 2020' 8.43]
 ['Goulburn - AMHS' 'Jan - Mar 2021' 3.15]
 ['Goulburn - AMHS' 'Apr - Jun 2021' 1.89]
 ['Grampians - AMHS' 'Apr - Jun 2020' 11.97]
 ['Grampians - AMHS' 'Jul - Sep 2020' 12.17]
 ['Grampians - AMHS' 'Oct - Dec 2020' 16.58]
 ['Grampians - AMHS' 'Jan - Mar 2021' 11.04]
 ['Grampians - AMHS' 'Apr - Jun 2021' 12.92]
 ['Inner & North West - Aged AMHS' 'Apr - Jun 2020' 2.09]
 ['Inner & North West - Aged AMHS' 'Jul - Sep 2020' 0.0]
 ['Inner & North West - Aged AMHS' 'Oct - Dec 2020' 3.06]
 ['Inner & North West - Aged AMHS' 'Jan - Mar 2021' 0.85]
 ['Inner & North West - Aged AMHS' 'Apr - Jun 2021' 0.84]
 ['Inner South East - Adult AMHS' 'Apr - Jun 2020' 4.71]
 ['Inner South East - Adult AMHS' 'Jul - Sep 2020' 6.72]
 ['Inner South East - Adult AMHS' 'Oct - Dec 2020' 8.75]
 ['Inner South East - Adult AMHS' 'Jan - Mar 2021' 8.39]
 ['Inner South East - Adult AMHS' 'Apr - Jun 2021' 8.9]
 ['Inner South East - Aged AMHS' 'Apr - Jun 2020' 0.0]
 ['Inner South East - Aged AMHS' 'Jul - Sep 2020' 0.0]
 ['Inner South East - Aged AMHS' 'Oct - Dec 2020' 0.0]
 ['Inner South East - Aged AMHS' 'Jan - Mar 2021' 0.0]
 ['Inner South East - Aged AMHS' 'Apr - Jun 2021' 0.0]
 ['Inner Urban East - Adult AMHS' 'Apr - Jun 2020' 1.29]
 ['Inner Urban East - Adult AMHS' 'Jul - Sep 2020' 1.39]
 ['Inner Urban East - Adult AMHS' 'Oct - Dec 2020' 1.33]
 ['Inner Urban East - Adult AMHS' 'Jan - Mar 2021' 0.94]
 ['Inner Urban East - Adult AMHS' 'Apr - Jun 2021' 6.04]
 ['Inner Urban East - Aged AMHS' 'Apr - Jun 2020' 2.34]
 ['Inner Urban East - Aged AMHS' 'Jul - Sep 2020' 0.81]
 ['Inner Urban East - Aged AMHS' 'Oct - Dec 2020' 0.68]
 ['Inner Urban East - Aged AMHS' 'Jan - Mar 2021' 0.61]
 ['Inner Urban East - Aged AMHS' 'Apr - Jun 2021' 0.61]
 ['Inner West - Adult AMHS' 'Apr - Jun 2020' 14.23]
 ['Inner West - Adult AMHS' 'Jul - Sep 2020' 4.96]
 ['Inner West - Adult AMHS' 'Oct - Dec 2020' 3.83]
 ['Inner West - Adult AMHS' 'Jan - Mar 2021' 7.95]
 ['Inner West - Adult AMHS' 'Apr - Jun 2021' 6.25]
 ['Loddon - AMHS' 'Apr - Jun 2020' 4.72]
 ['Loddon - AMHS' 'Jul - Sep 2020' 5.31]
 ['Loddon - AMHS' 'Oct - Dec 2020' 4.97]
 ['Loddon - AMHS' 'Jan - Mar 2021' 3.71]
 ['Loddon - AMHS' 'Apr - Jun 2021' 2.54]
 ['Mid & South West - Aged AMHS' 'Apr - Jun 2020' 0.0]
 ['Mid & South West - Aged AMHS' 'Jul - Sep 2020' 0.66]
 ['Mid & South West - Aged AMHS' 'Oct - Dec 2020' 0.59]
 ['Mid & South West - Aged AMHS' 'Jan - Mar 2021' 7.69]
 ['Mid & South West - Aged AMHS' 'Apr - Jun 2021' 0.0]
 ['Mid West - Adult AMHS' 'Apr - Jun 2020' 26.64]
 ['Mid West - Adult AMHS' 'Jul - Sep 2020' 26.85]
 ['Mid West - Adult AMHS' 'Oct - Dec 2020' 28.33]
 ['Mid West - Adult AMHS' 'Jan - Mar 2021' 9.25]
 ['Mid West - Adult AMHS' 'Apr - Jun 2021' 17.49]
 ['Middle South - Adult AMHS' 'Apr - Jun 2020' 3.88]
 ['Middle South - Adult AMHS' 'Jul - Sep 2020' 3.92]
 ['Middle South - Adult AMHS' 'Oct - Dec 2020' 3.38]
 ['Middle South - Adult AMHS' 'Jan - Mar 2021' 7.22]
 ['Middle South - Adult AMHS' 'Apr - Jun 2021' 3.76]
 ['Middle South - Aged AMHS' 'Apr - Jun 2020' 0.0]
 ['Middle South - Aged AMHS' 'Jul - Sep 2020' 0.0]
 ['Middle South - Aged AMHS' 'Oct - Dec 2020' 0.57]
 ['Middle South - Aged AMHS' 'Jan - Mar 2021' 0.0]
 ['Middle South - Aged AMHS' 'Apr - Jun 2021' 0.28]
 ['North East - Adult AMHS' 'Apr - Jun 2020' 11.49]
 ['North East - Adult AMHS' 'Jul - Sep 2020' 6.05]
 ['North East - Adult AMHS' 'Oct - Dec 2020' 2.65]
 ['North East - Adult AMHS' 'Jan - Mar 2021' 5.57]
 ['North East - Adult AMHS' 'Apr - Jun 2021' 3.44]
 ['North East and Border AMHS' 'Apr - Jun 2020' 7.22]
 ['North East and Border AMHS' 'Jul - Sep 2020' 7.49]
 ['North East and Border AMHS' 'Oct - Dec 2020' 4.58]
 ['North East and Border AMHS' 'Jan - Mar 2021' 8.91]
 ['North East and Border AMHS' 'Apr - Jun 2021' 2.09]
 ['North Eastern - CAMHS AMHS' 'Apr - Jun 2020' 62.82]
 ['North Eastern - CAMHS AMHS' 'Jul - Sep 2020' 12.94]
 ['North Eastern - CAMHS AMHS' 'Oct - Dec 2020' 9.17]
 ['North Eastern - CAMHS AMHS' 'Jan - Mar 2021' 17.69]
 ['North Eastern - CAMHS AMHS' 'Apr - Jun 2021' 5.49]
 ['North West - Adult AMHS' 'Apr - Jun 2020' 7.77]
 ['North West - Adult AMHS' 'Jul - Sep 2020' 15.72]
 ['North West - Adult AMHS' 'Oct - Dec 2020' 9.04]
 ['North West - Adult AMHS' 'Jan - Mar 2021' 25.78]
 ['North West - Adult AMHS' 'Apr - Jun 2021' 18.19]
 ['North Western - CAMHS AMHS' 'Apr - Jun 2020' 25.27]
 ['North Western - CAMHS AMHS' 'Jul - Sep 2020' 9.73]
 ['North Western - CAMHS AMHS' 'Oct - Dec 2020' 9.23]
 ['North Western - CAMHS AMHS' 'Jan - Mar 2021' 4.02]
 ['North Western - CAMHS AMHS' 'Apr - Jun 2021' 10.74]
 ['Northern - Adult AMHS' 'Apr - Jun 2020' 13.82]
 ['Northern - Adult AMHS' 'Jul - Sep 2020' 20.86]
 ['Northern - Adult AMHS' 'Oct - Dec 2020' 16.75]
 ['Northern - Adult AMHS' 'Jan - Mar 2021' 11.87]
 ['Northern - Adult AMHS' 'Apr - Jun 2021' 11.35]
 ['Northern & North East - Aged AMHS' 'Apr - Jun 2020' 0.0]
 ['Northern & North East - Aged AMHS' 'Jul - Sep 2020' 0.0]
 ['Northern & North East - Aged AMHS' 'Oct - Dec 2020' 0.0]
 ['Northern & North East - Aged AMHS' 'Jan - Mar 2021' 0.0]
 ['Northern & North East - Aged AMHS' 'Apr - Jun 2021' 0.0]
 ['Northern Mallee - AMHS' 'Apr - Jun 2020' 10.35]
 ['Northern Mallee - AMHS' 'Jul - Sep 2020' 10.99]
 ['Northern Mallee - AMHS' 'Oct - Dec 2020' 12.84]
 ['Northern Mallee - AMHS' 'Jan - Mar 2021' 12.1]
 ['Northern Mallee - AMHS' 'Apr - Jun 2021' 8.96]
 ['Orygen Youth Area Mental Health Service' 'Apr - Jun 2020' 0.0]
 ['Orygen Youth Area Mental Health Service' 'Jul - Sep 2020' 2.17]
 ['Orygen Youth Area Mental Health Service' 'Oct - Dec 2020' 2.79]
 ['Orygen Youth Area Mental Health Service' 'Jan - Mar 2021' 2.16]
 ['Orygen Youth Area Mental Health Service' 'Apr - Jun 2021' 13.24]
 ['Outer East - Adult AMHS' 'Apr - Jun 2020' 18.93]
 ['Outer East - Adult AMHS' 'Jul - Sep 2020' 20.76]
 ['Outer East - Adult AMHS' 'Oct - Dec 2020' 10.95]
 ['Outer East - Adult AMHS' 'Jan - Mar 2021' 7.23]
 ['Outer East - Adult AMHS' 'Apr - Jun 2021' 12.21]
 ['Peninsula - Adult AMHS' 'Apr - Jun 2020' 2.19]
 ['Peninsula - Adult AMHS' 'Jul - Sep 2020' 2.21]
 ['Peninsula - Adult AMHS' 'Oct - Dec 2020' 2.97]
 ['Peninsula - Adult AMHS' 'Jan - Mar 2021' 0.0]
 ['Peninsula - Adult AMHS' 'Apr - Jun 2021' 0.38]
 ['Peninsula - Aged AMHS' 'Apr - Jun 2020' 0.0]
 ['Peninsula - Aged AMHS' 'Jul - Sep 2020' 0.0]
 ['Peninsula - Aged AMHS' 'Oct - Dec 2020' 0.0]
 ['Peninsula - Aged AMHS' 'Jan - Mar 2021' 0.0]
 ['Peninsula - Aged AMHS' 'Apr - Jun 2021' 0.0]
 ['South Eastern - CAMHS AMHS' 'Apr - Jun 2020' 34.26]
 ['South Eastern - CAMHS AMHS' 'Jul - Sep 2020' 18.45]
 ['South Eastern - CAMHS AMHS' 'Oct - Dec 2020' 11.38]
 ['South Eastern - CAMHS AMHS' 'Jan - Mar 2021' 12.64]
 ['South Eastern - CAMHS AMHS' 'Apr - Jun 2021' 3.22]
 ['South West - Adult AMHS' 'Apr - Jun 2020' 9.65]
 ['South West - Adult AMHS' 'Jul - Sep 2020' 10.5]
 ['South West - Adult AMHS' 'Oct - Dec 2020' 16.58]
 ['South West - Adult AMHS' 'Jan - Mar 2021' 14.57]
 ['South West - Adult AMHS' 'Apr - Jun 2021' 15.21]
 ['Statewide' 'Apr - Jun 2020' 9.36]
 ['Statewide' 'Jul - Sep 2020' 8.1]
 ['Statewide' 'Oct - Dec 2020' 8.04]
 ['Statewide' 'Jan - Mar 2021' 7.54]
 ['Statewide' 'Apr - Jun 2021' 6.54]]

In [11]:
# Check and delete null values
df1 = df1.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [12]:
df1.columns = ["Organisation Description","Calendar Quarter Name","Table Value"]

In [14]:
df2 = df1

In [45]:
df2['A'], df2['B'], df2['c'] , df2['d'] = df2['Calendar Quarter Name'].str.split(r"\s+",n =3).str

<ipython-input-45-3c262500af82>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df2['A'], df2['B'], df2['c'] , df2['d'] = df2['Calendar Quarter Name'].str.split(r"\s+",n =3).str

In [48]:
df1 = df2.drop(columns = ["B"])

In [51]:
df1.rename(columns ={"A":"Calendar quarter first month name","c":"Calendar quarter last month name","d":"year"},inplace = True)

In [54]:
df1

,Organisation Description,quarter,Calendar Quarter Name,Table Value,Calendar quarter first month name,Calendar quarter last month name,year
0,Albury - Adult AMHS,Apr,Apr - Jun 2020,13.28,Apr,Jun,2020
1,Albury - Adult AMHS,Jul,Jul - Sep 2020,8.35,Jul,Sep,2020
2,Albury - Adult AMHS,Oct,Oct - Dec 2020,3.88,Oct,Dec,2020
3,Albury - Adult AMHS,Jan,Jan - Mar 2021,2.41,Jan,Mar,2021
4,Albury - Adult AMHS,Apr,Apr - Jun 2021,3.34,Apr,Jun,2021
...,...,...,...,...,...,...,...
175,Statewide,Apr,Apr - Jun 2020,9.36,Apr,Jun,2020
176,Statewide,Jul,Jul - Sep 2020,8.10,Jul,Sep,2020
177,Statewide,Oct,Oct - Dec 2020,8.04,Oct,Dec,2020
178,Statewide,Jan,Jan - Mar 2021,7.54,Jan,Mar,2021
179,Statewide,Apr,Apr - Jun 2021,6.54,Apr,Jun,2021

In [53]:
df1.insert(1,"quarter",df1["Calendar quarter first month name"])

In [74]:
for i in range(len(df1.quarter)):
    if df1.quarter.loc[i] == 'Jan':
        df1.quarter.loc[i] = 1
    elif df1.quarter.loc[i] == 'Apr':
        df1.quarter.loc[i] = 2
    elif df1.quarter.loc[i] == "Jul":
        df1.quarter.loc[i] = 3
    elif df1.quarter.loc[i] == "Oct":
        df1.quarter.loc[i] = 4

In [75]:
df1

,Organisation Description,quarter,Calendar Quarter Name,Table Value,Calendar quarter first month name,Calendar quarter last month name,year
0,Albury - Adult AMHS,2,Apr - Jun 2020,13.28,Apr,Jun,2020
1,Albury - Adult AMHS,3,Jul - Sep 2020,8.35,Jul,Sep,2020
2,Albury - Adult AMHS,4,Oct - Dec 2020,3.88,Oct,Dec,2020
3,Albury - Adult AMHS,1,Jan - Mar 2021,2.41,Jan,Mar,2021
4,Albury - Adult AMHS,2,Apr - Jun 2021,3.34,Apr,Jun,2021
...,...,...,...,...,...,...,...
175,Statewide,2,Apr - Jun 2020,9.36,Apr,Jun,2020
176,Statewide,3,Jul - Sep 2020,8.10,Jul,Sep,2020
177,Statewide,4,Oct - Dec 2020,8.04,Oct,Dec,2020
178,Statewide,1,Jan - Mar 2021,7.54,Jan,Mar,2021
179,Statewide,2,Apr - Jun 2021,6.54,Apr,Jun,2021

In [76]:
df1.to_csv('data1.csv')